name: "Check for newer platform/extension versions"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.QUARKIVERSE_BOT_TOKEN }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token
          fetch-depth: 0 # otherwise, you will get failed to push refs to dest repo errors

      - name: Run Check Updates script
        uses: jbangdev/jbang-action@v0.78.0
        with:
          script: catalog_check_updates@quarkusio
          scriptargs: --working-directory=.

      - name: Push changes to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.QUARKIVERSE_BOT_TOKEN }}
          branch: main
