name: "Deploy GitHub Pages static website"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "platforms/**"
      - "extensions/**"
jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git author
        run: |
          git config --global user.name "quarkusbot"
          git config --global user.email "quarkusbot@users.noreply.github.com"

      - uses: actions/checkout@v2
        name: Checkout main branch
        with:
          path: catalog
          ref: main

      - uses: actions/checkout@v2
        name: Checkout pages branch
        with:
          path: pages
          ref: pages
          token: ${{ secrets.REGISTRY_QUARKUS_BOT_PAT }}

      - name: Remove Maven Directory
        run: rm -rfv pages/maven

      - name: Generate Static Maven Repository
        uses: jbangdev/jbang-action@v0.78.0
        with:
          script: catalog/.github/workflows/deploy.java
          scriptargs: --working-directory=catalog -o pages/maven
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Commit and push changes
        run: |
          cd catalog
          export TAG=$(git rev-parse --short=7 HEAD)
          cd ../pages
          git add . && git commit -m "Repository generated from ${TAG}" && git push
