name: "Publish to the Extension Registry"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure Git author
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
      - name: Run Publish Catalog script
        uses: jbangdev/jbang-action@v0.77.0
        with:
          script: publishcatalog@quarkusio
          scriptargs: --working-directory=.
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push changes to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
