name: "Publish to the Extension Registry"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "platforms/**"
      - "extensions/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Publish Catalog script
        uses: jbangdev/jbang-action@v0.90.1
        with:
          script: catalog_publish@quarkusio
          scriptargs: --working-directory=. --all
          trust: https://github.com/quarkusio/
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
